---
- name: Clear System Caches (RAM & Disk)
  hosts: all
  become: yes
  tasks:

    # ---------------------------------------------------------
    # 1. PRE-CHECKS (Measure sizes before cleaning)
    # ---------------------------------------------------------
    - name: Measure Yum cache size before cleaning
      ansible.builtin.shell: du -sh /var/cache/yum | cut -f1
      register: yum_cache_size_before
      changed_when: false
      ignore_errors: true

    - name: Get current free memory (MB) before clearing
      ansible.builtin.shell: free -m | awk '/^Mem:/{print $4}'
      register: mem_free_before
      changed_when: false

    # ---------------------------------------------------------
    # 2. CLEAR DISK CACHE (Yum)
    # ---------------------------------------------------------
    - name: Clean Yum metadata and package cache
      ansible.builtin.command:
        cmd: yum clean all
      register: yum_output
      changed_when: "'0 package files removed' not in yum_output.stdout"

    # ---------------------------------------------------------
    # 3. CLEAR RAM CACHE (PageCache, dentries, and inodes)
    # ---------------------------------------------------------
    - name: Sync filesystem buffers before dropping cache
      ansible.builtin.command: sync

    - name: Drop RAM Caches (Free up Memory)
      ansible.builtin.shell: echo 3 > /proc/sys/vm/drop_caches
      args:
        executable: /bin/bash
      
    # ---------------------------------------------------------
    # 4. POST-CHECKS & REPORTING
    # ---------------------------------------------------------
    - name: Get free memory (MB) after clearing
      ansible.builtin.shell: free -m | awk '/^Mem:/{print $4}'
      register: mem_free_after
      changed_when: false

    - name: Display Cleanup Summary
      ansible.builtin.debug:
        msg:
          - "======================================================="
          - "   SUCCESSFULLY CLEARED SYSTEM CACHES"
          - "======================================================="
          - "Disk Space Freed (Yum): {{ yum_cache_size_before.stdout | default('0B') }}"
          - "RAM Freed (Est):        {{ (mem_free_after.stdout | int) - (mem_free_before.stdout | int) }} MB"
          - "Current Free RAM:       {{ mem_free_after.stdout }} MB"
          - "======================================================="
