---
- name: AWS Linux System Cleanup
  hosts: all
  become: yes
  vars:
    file_age_seconds: "86400"
    clean_temp_dirs: true
    clean_yum_cache: true
    clean_journal_logs: true
    temp_paths:
      - /tmp
      - /var/tmp

  tasks:
    # 1. Clear Standard Temporary Directories
    - name: Find temporary files older than {{ file_age_seconds }} seconds
      ansible.builtin.find:
        paths: "{{ item }}"
        age: "{{ file_age_seconds }}"
        recurse: yes
        file_type: file
      loop: "{{ temp_paths }}"
      register: files_to_delete
      when: clean_temp_dirs
      tags: ['temp']

    - name: Remove found temporary files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.results | map(attribute='files') | list | flatten }}"
      loop_control:
        label: "{{ item.path }}"
      when: clean_temp_dirs
      tags: ['temp']

    # 2. Clean YUM Cache (FIXED TASK)
    - name: Clean Yum cache (frees /var/cache/yum)
      ansible.builtin.command:
        cmd: yum clean all
      # 'args: warn: false' REMOVED here
      when: clean_yum_cache
      tags: ['yum']

    # 3. Vacuum Systemd Journals
    - name: Vacuum systemd journals older than 2 days
      ansible.builtin.command:
        cmd: journalctl --vacuum-time=2d
      register: journal_out
      changed_when: "'0B' not in journal_out.stderr"
      when: clean_journal_logs
      tags: ['logs']
