---
- name: Ubuntu System Cleanup
  hosts: all
  become: yes
  vars:
    # Safety: Only delete files older than 1 day (86400 seconds)
    file_age_seconds: "86400"
    
    # Toggle specific cleanup tasks
    clean_temp_dirs: true
    clean_apt_cache: true
    clean_journal_logs: true
    
    # Paths to scan for temp files
    temp_paths:
      - /tmp
      - /var/tmp

  tasks:
    # ---------------------------------------------------------
    # 1. Clear Standard Temporary Directories
    # ---------------------------------------------------------
    - name: Find temporary files older than {{ file_age_seconds }} seconds
      ansible.builtin.find:
        paths: "{{ item }}"
        age: "{{ file_age_seconds }}"
        age_stamp: mtime
        recurse: yes
        file_type: file
      loop: "{{ temp_paths }}"
      register: files_to_delete
      when: clean_temp_dirs
      tags: [ 'temp' ]

    - name: Remove found temporary files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.results | map(attribute='files') | list | flatten }}"
      loop_control:
        label: "{{ item.path }}"
      when: clean_temp_dirs
      tags: [ 'temp' ]

    # ---------------------------------------------------------
    # 2. Clear APT Cache (Specific to Ubuntu/Debian)
    # ---------------------------------------------------------
    - name: Clean APT cache (frees /var/cache/apt/archives)
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes
      when: clean_apt_cache
      tags: [ 'apt' ]

    # ---------------------------------------------------------
    # 3. Vacuum Systemd Journals (Log cleanup)
    # ---------------------------------------------------------
    - name: Vacuum systemd journals older than 2 days
      ansible.builtin.command:
        cmd: journalctl --vacuum-time=2d
      register: journal_out
      changed_when: "'0B' not in journal_out.stderr"
      when: clean_journal_logs
      tags: [ 'logs' ]
