---
- name: Connectivity Validation
  hosts: all
  gather_facts: no
  # We assume 'become: yes' is enabled globally or in the Job Template,
  # so we must disable it for the local ping task.

  tasks:
    # 1. Network Ping (Runs on AWX, targets Server)
    - name: Network Reachability Check
      ansible.builtin.command: "ping -c 2 {{ inventory_hostname }}"
      delegate_to: localhost
      become: false  # <--- FIX: Do not use sudo inside AWX container
      register: net_ping
      ignore_errors: yes
      changed_when: false

    # 2. SSH Ping (Runs on Server)
    - name: SSH Connectivity Check
      ansible.builtin.ping:
      register: ssh_ping
      ignore_errors: yes

    # 3. Final Simple Output
    - name: Validation Result
      ansible.builtin.debug:
        msg: >-
          STATUS: {{ 'SUCCESS' if (net_ping.rc == 0 and ssh_ping.ping is defined) else 'FAILED' }} 
          [Network: {{ 'OK' if net_ping.rc == 0 else 'DOWN' }} | SSH: {{ 'OK' if ssh_ping.ping is defined else 'DOWN' }}]
