---
- name: Connectivity Validation
  hosts: all
  gather_facts: no
  # Ensure 'become: yes' is disabled for the local task below
  
  tasks:
    # 1. Network Ping (Runs on AWX, targets Server)
    - name: Network Reachability Check
      ansible.builtin.command: "ping -c 2 {{ inventory_hostname }}"
      delegate_to: localhost
      become: false
      register: net_ping
      ignore_errors: yes
      changed_when: false

    # 2. SSH Ping (Runs on Server)
    - name: SSH Connectivity Check
      ansible.builtin.ping:
      register: ssh_ping
      ignore_errors: yes

    # 3. Final Output (Logic: If SSH works OR Ping works -> Success)
    - name: Validation Result
      ansible.builtin.debug:
        msg: >-
          {% if ssh_ping.ping is defined %}
          SUCCESS: Network connectivity is possible. (SSH Verified. Ping status ignored/blocked).
          {% elif net_ping.rc == 0 %}
          WARNING: Network connectivity is possible (Ping OK), but SSH failed.
          {% else %}
          FAILED: Server is unreachable via both Network and SSH.
          {% endif %}
