---
- name: Start Apache on AWS Linux
  hosts: all
  become: yes          # <- IMPORTANT for Amazon Linux (ec2-user needs sudo)
  become_method: sudo  # optional, but explicit
  tasks:
    - name: Install httpd package (if not installed)
      yum:
        name: httpd
        state: present

    - name: Ensure httpd service is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes
