---
- name: Start Apache on AWS Linux
  hosts: all
  become: yes
  tasks:
    - name: Install httpd package (if not installed)
      yum:
        name: httpd
        state: present

    - name: Ensure httpd service is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes
