---
- name: Start and verify Apache on AWS Linux
  hosts: all
  become: yes

  tasks:
    - name: Install Apache (httpd)
      package:
        name: httpd
        state: present

    - name: Ensure Apache is started and enabled on boot
      service:
        name: httpd
        state: started
        enabled: true
      register: apache_service

    - name: Show result of service start
      debug:
        var: apache_service

    - name: Check status via systemctl
      shell: systemctl is-active httpd
      register: httpd_status
      changed_when: false

    - name: Show systemctl status (is-active)
      debug:
        var: httpd_status.stdout
