---
- name: Install and manage Apache on Linux
  hosts: all
  become: yes

  vars:
    apache_pkg: >-
      {{ 'httpd' 
         if ansible_facts.pkg_mgr in ['yum', 'dnf'] 
         else 'apache2' }}
    apache_service: >-
      {{ 'httpd' 
         if ansible_facts.os_family in ['RedHat', 'Amazon'] 
         else 'apache2' }}

  tasks:
    - name: Show detected OS and package manager
      debug:
        msg: "OS family={{ ansible_facts.os_family }}, pkg_mgr={{ ansible_facts.pkg_mgr }}"

    - name: Install Apache
      package:
        name: "{{ apache_pkg }}"
        state: present

    - name: Ensure Apache is started and enabled on boot
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true

    - name: Restart Apache
      service:
        name: "{{ apache_service }}"
        state: restarted
